import { Migration } from '../migrator';

/**
 * Periods where the user removed (or moved) the movement generated by a rule, so
 * the materializer does not create it again.
 */
export const recurringSkips: Migration = {
  version: 4,
  name: 'recurring rule skipped periods',
  up(db) {
    db.exec(`
      CREATE TABLE recurring_rule_skips (
        rule_id TEXT NOT NULL REFERENCES recurring_rules(id) ON DELETE CASCADE,
        year    INTEGER NOT NULL,
        month   INTEGER NOT NULL,
        PRIMARY KEY (rule_id, year, month)
      );
    `);
  },
};
